#       --------- + SimpleBroadcast by Ziga Zajc + -------   #
#                                                            #
#                            Config                          #
#                                                            #
#       --------- + ------------------------- + ----------   #
#
#       You can use chat colors:
#                ________________________
#               |   code: | color:       |
#               |________________________|
#               |     &0  |	Black	     |
#               |     &1  |	Dark Blue	 |
#               |     &2  |	Dark Green	 |
#               |     &3  |	Dark Aqua	 |
#               |     &4  |	Dark Red	 |
#               |     &5  |	Dark Purple	 |
#               |     &6  |	Gold	     |
#               |     &7  |	Gray	     |
#               |     &8  |	Dark Gray	 |
#               |     &9  |	Blue	     |
#               |     &a  |	Green	     |
#               |     &b  |	Aqua	     |
#               |     &c  |	Red	         |
#               |     &d  |	Light Purple |
#               |     &e  |	Yellow	     |
#               |     &f  |	White	     |
#               |     &k  |	Obfuscated	 |
#               |     &l  |	Bold	     |
#               |     &m  |	Strikethrough|
#               |     &n  |	Underline	 |
#               |     &o  |	Italic	     |
#               |     &r  |	Reset	     |
#               |________________________|
#
#----------------------------------------------------------
#                      Colors
#----------------------------------------------------------
color_prefix: ";"
#----------------------------------------------------------
#                      Channels
#----------------------------------------------------------
channels:
  all:
    format: "&7[&6Broadcast&7] {message}"
    senderPermission: "broadcast.send.all"
    receiverPermission: null
    bungee: false
  players:
    format: "&7[&6Broadcast&7] {message}"
    senderPermission: "broadcast.send.player"
    receiverPermission: "broadcast.player"
    bungee: false
  admins:
    format: "&7[&cAB&7] {message}"
    senderPermission: "broadcast.send.admin"
    receiverPermission: "broadcast.admin"
    bungee: false
#----------------------------------------------------------
#                        Bungee
#----------------------------------------------------------
# If you plan to broadcast messages between multiple servers through bungeecord, enable this feature and place SimpleBroadcast plugin to bungeecord server as well.
bungee_enabled: false
# The name of the bungee server (Can be the same as in bugeecord)
server_name: "Survival"